version: '3'

services:

  db:
    image: postgres:15.4
    container_name: api-key-steward-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db-network

  api-key-steward:
    image: api-key-steward:latest
    container_name: api-key-steward
    environment:
      - AUTH_JWKS_URL=https://dev-hx1i28xxvaqf6we3.uk.auth0.com/.well-known/jwks.json
      - AUTH_JWT_ALLOWED_ISSUER=https://dev-hx1i28xxvaqf6we3.uk.auth0.com/
      - AUTH_JWT_AUDIENCE=https://api-key-steward.web-app.example.com
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=example
    ports:
          - 8080:8080
    networks:
      - db-network

volumes:
  pgdata:

networks:
  db-network:
    driver: bridge
