services:

  db:
    image: postgres:15.4
    container_name: api-key-steward-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

