services:

  db:
    image: postgres:15.4
    container_name: api-key-steward-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  vault-server:
    image: hashicorp/vault:latest
    container_name: vault-server
    ports:
      - 8200:8200
    restart: always
    volumes:
      - ~/docker-vault/logs:/vault/logs
      - ~/docker-vault/file:/vault/file
      - ~/docker-vault/config:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json

volumes:
  pgdata:

